# Generated by Django 4.2.6 on 2023-12-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('name',)},
        ),
    ]
